version: '2'

services:
  traefik:
    image: traefik:1.5.4
    restart: always
    ports:
      - 80:80
      - 443:443
    expose:
      - 8080
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/hartzell/traefik-experiment/traefik.toml:/traefik.toml
      - /home/hartzell/traefik-experiment/acme.json:/acme.json
    container_name: traefik
    labels:
      - "traefik.backend=traefik"
      - "traefik.docker.network=web"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:bunny.do.alerce.com;PathPrefixStrip:/api"
      - "traefik.enable=true"

  whoami:
    image: emilevauge/whoami #A container that exposes an API to show it's IP address
    labels:
      - "traefik.frontend.rule=Path:/whoami"
      - "traefik.enable=true"
    networks:
      - web

networks:
  web:
    external: true
